const products=[];
const art={marcapaginas:['☾','✿','☀'],imanes:['♡','⌂','❀'],stickers:['▤','✦','“”']};
for(let n=1;n<=14;n++)products.push({id:n,name:`Marcapáginas con imán ${String(n).padStart(2,'0')}`,category:'marcapaginas',categoryLabel:'Marcapáginas con imán',price:2000,image:`assets/marcapaginas_imagenes/marcapagina_imagen_${n}.png`,description:'Marcapáginas con imán hecho a mano para acompañar tus lecturas.'});
for(let n=1;n<=22;n++)products.push({id:100+n,name:`Imán ilustrado ${String(n).padStart(2,'0')}`,category:'imanes',categoryLabel:'Imanes',price:350,image:`assets/imanes_imagenes/iman_imagen_${n}.png`,description:'Imán ilustrado hecho a mano. Tiene hasta 5 cm de altura.'});
for(let n=1;n<=18;n++)products.push({id:200+n,name:`Sticker ilustrado ${String(n).padStart(2,'0')}`,category:'stickers',categoryLabel:'Stickers',price:200,image:`assets/sticker_imagenes/sticker_imagen_${n}.png`,description:'Sticker ilustrado para decorar tus objetos favoritos.'});
const state={filter:'all',selected:null,cart:[]},money=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0});
const grid=document.querySelector('[data-products]'),modal=document.querySelector('[data-modal]'),cart=document.querySelector('[data-cart]');
function productArt(p){const icon=art[p.category][(p.id%100-1)%3];return `<div class="art"><img src="${p.image}" alt="" onerror="this.remove()"><span>${icon}</span><small>Último Capítulo<br>Eich</small></div>`}
function renderProducts(){const visible=products.filter(p=>state.filter==='all'||p.category===state.filter);grid.innerHTML=visible.map(p=>`<article class="product"><button data-view="${p.id}" aria-label="Ver ${p.name}">${productArt(p)}</button><div class="product-info"><p>${p.categoryLabel}</p><div><h3>${p.name}</h3><strong>${money.format(p.price)} c/u</strong></div></div></article>`).join('');document.querySelector('[data-count]').textContent=`${visible.length} detalles para descubrir`;document.querySelector('[data-magnet-note]').hidden=!['all','imanes'].includes(state.filter)}
function openProduct(id){const p=products.find(x=>x.id===+id);state.selected=p;document.querySelector('[data-modal-art]').innerHTML=productArt(p);document.querySelector('[data-modal-category]').textContent=p.categoryLabel;document.querySelector('[data-modal-title]').textContent=p.name;document.querySelector('[data-modal-description]').textContent=p.description;document.querySelector('[data-modal-price]').textContent=`${money.format(p.price)} c/u${p.category==='stickers'?' · 5 por $900':p.category==='imanes'?' · 5 por $1.600':''}`;modal.classList.add('show')}
function pricing(){const subtotal=state.cart.reduce((a,p)=>a+p.price*p.quantity,0);const q=c=>state.cart.filter(p=>p.category===c).reduce((a,p)=>a+p.quantity,0);const discount=Math.floor(q('stickers')/5)*100+Math.floor(q('imanes')/5)*150;return{subtotal,discount,total:subtotal-discount}}
function renderCart(){const quantity=state.cart.reduce((a,p)=>a+p.quantity,0),cost=pricing();document.querySelector('.cart-count').textContent=quantity;document.querySelector('[data-subtotal]').textContent=money.format(cost.subtotal);document.querySelector('[data-total]').textContent=money.format(cost.total);document.querySelector('[data-empty]').hidden=!!quantity;document.querySelector('[data-discount]').hidden=!cost.discount;document.querySelector('[data-discount-value]').textContent=`−${money.format(cost.discount)}`;document.querySelector('[data-cart-items]').innerHTML=state.cart.map(p=>`<div class="cart-item"><div><strong>${p.name}</strong><span>${money.format(p.price)} c/u</span></div><div class="quantity"><button data-qty="${p.id}" data-d="-1">−</button><b>${p.quantity}</b><button data-qty="${p.id}" data-d="1">+</button></div></div>`).join('')}
function openCart(){cart.classList.add('open')}function closeCart(){cart.classList.remove('open')}function closeModal(){modal.classList.remove('show')}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});grid.onclick=e=>{const b=e.target.closest('[data-view]');if(b)openProduct(b.dataset.view)};document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=closeModal);document.querySelector('[data-add]').onclick=()=>{const item=state.cart.find(p=>p.id===state.selected.id);item?item.quantity++:state.cart.push({...state.selected,quantity:1});renderCart();closeModal();openCart()};document.querySelector('[data-open-cart]').onclick=openCart;document.querySelectorAll('[data-close-cart]').forEach(b=>b.onclick=closeCart);document.querySelector('[data-cart-items]').onclick=e=>{const b=e.target.closest('[data-qty]');if(!b)return;const p=state.cart.find(x=>x.id===+b.dataset.qty);p.quantity+=+b.dataset.d;if(!p.quantity)state.cart=state.cart.filter(x=>x!==p);renderCart()};document.querySelector('[data-whatsapp]').onclick=()=>{if(!state.cart.length)return;const list=state.cart.map(p=>`• ${p.name} x${p.quantity}`).join('\n'),cost=pricing();window.open(`https://wa.me/5493794136245?text=${encodeURIComponent(`¡Hola! Me gustaría consultar por estos productos de Último Capítulo Eich:\n\n${list}\n\nTotal estimado: ${money.format(cost.total)}`)}`,'_blank','noopener')};renderProducts();renderCart();
